// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWDcGdG7pz5YSX5FDM1WTDiF6nxreBl6w',
    appId: '1:1094679276562:web:8c14f31c4749035187bccb',
    messagingSenderId: '1094679276562',
    projectId: 'libre-soft',
    authDomain: 'libre-soft.firebaseapp.com',
    storageBucket: 'libre-soft.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtUYn4ILVh0_49WFvudPbuBAHvm5EWTVg',
    appId: '1:1094679276562:android:adf88f85511449d787bccb',
    messagingSenderId: '1094679276562',
    projectId: 'libre-soft',
    storageBucket: 'libre-soft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAszwi4ue3zsvFwUxszg0vISpiEFkhGJjc',
    appId: '1:1094679276562:ios:21d31b186e3812bc87bccb',
    messagingSenderId: '1094679276562',
    projectId: 'libre-soft',
    storageBucket: 'libre-soft.appspot.com',
    iosBundleId: 'com.libresoft.elvis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAszwi4ue3zsvFwUxszg0vISpiEFkhGJjc',
    appId: '1:1094679276562:ios:e4852797c358aa0987bccb',
    messagingSenderId: '1094679276562',
    projectId: 'libre-soft',
    storageBucket: 'libre-soft.appspot.com',
    iosBundleId: 'com.example.libresoftElvis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWDcGdG7pz5YSX5FDM1WTDiF6nxreBl6w',
    appId: '1:1094679276562:web:ee49f74e403e2a8b87bccb',
    messagingSenderId: '1094679276562',
    projectId: 'libre-soft',
    authDomain: 'libre-soft.firebaseapp.com',
    storageBucket: 'libre-soft.appspot.com',
  );
}
